# -*- coding: utf-8 -*-
"""IrisFlowerML0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xEkZAPHJj-WJQgQ9_hIl7hA3qh4bz8d
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# %matplotlib inline

column=['Sepal length','Sepal width','Petal length','Petal width','Class_label']
df=pd.read_csv('iris.data',names=column)
df.head()

from google.colab import drive
drive.mount('/content/drive')

df.describe()

sns.pairplot(df,hue='Class_label')

data=df.values

X=data[:,0:4]
Y=data[:,4]
print(Y)

from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2)
print(Xtest)

from sklearn.svm import SVC
model_svc=SVC()
model_svc.fit(Xtrain,Ytrain)

prediction1=model_svc.predict(Xtest)

from sklearn.metrics import accuracy_score
print(accuracy_score(Ytest,prediction1))

from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(Xtrain,Ytrain)

prediction2=model_LR.predict(Xtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(Ytest,prediction2)*100)

from sklearn.tree import DecisionTreeClassifier
model_DTC=DecisionTreeClassifier()
model_DTC.fit(Xtrain,Ytrain)

prediction3=model_svc.predict(Xtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(Ytest,prediction3)*100)

# To check with other data

Xnew=[[3,2,1,0.2],[4.9,2.2,3.8,1.1],[5.2,2.5,4.6,1.9]]
predict=model_svc.predict(Xnew)
print('result is {}'.format(predict))